### ISSUE TITLE
[1 pt] Project Deployment - Group Task

### ISSUE THREAD

**Issue by patriciachrysy** [patriciachrysy/Web-Developers-Booking-App#13]
Link to the project:
[Web-Developers-Booking](https://github.com/users/patriciachrysy/projects/4)

## Team Members(4):

1.Team member 1 is @AbuTalha3 
2.Team member 2 is @richie1988 
3.Team member 3 is  @Samuelwanza 
4.Team member 4 is  @patriciachrysy 
## Kanban Board Group Task  Diagram
![chrome_K9RLjgh0Ry](https://github.com/patriciachrysy/Web-Developers-Booking-App/assets/97953658/c38ae002-4a92-4def-bff7-65aa4219b05c)

**Comment by Meltrust** [comment]
Hi,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!





![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️

According to the project requirements:

![image](https://github.com/patriciachrysy/Web-Developers-Booking-App/assets/57421823/90f9d686-12bd-457d-9a3e-f4d53b7aa14c)

Therefore:

- [ ] Make sure you include a direct link to the kanban board.
- [ ] Please write a note including how many people are on the team.
- [ ] Please include an screenshot of the kanban board.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Meltrust** [comment]
## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
